// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptionsProd {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHD0c9flUPewTvpE5lTPoscFNfI-9lU1w',
    appId: '1:381425611294:web:d8ae134bee67998fca740f',
    messagingSenderId: '381425611294',
    projectId: 'luna-prod-cbc3f',
    authDomain: 'luna-prod-cbc3f.firebaseapp.com',
    storageBucket: 'luna-prod-cbc3f.appspot.com',
    measurementId: 'G-4QC9X8FFPG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADAkYgqVP-MphtgqbQvgS_pMa8sIi2v70',
    appId: '1:381425611294:android:2f8148246a4e9084ca740f',
    messagingSenderId: '381425611294',
    projectId: 'luna-prod-cbc3f',
    storageBucket: 'luna-prod-cbc3f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFv5MC6XjZQKU3YSllU7YXnglxr4CQSCU',
    appId: '1:381425611294:ios:fd848a3573d1e589ca740f',
    messagingSenderId: '381425611294',
    projectId: 'luna-prod-cbc3f',
    storageBucket: 'luna-prod-cbc3f.appspot.com',
    iosBundleId: 'com.valjohn.luna.luna',
  );
}
