// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptionsStaging {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCX-9xem8opEOR3jNSw7GSW9AqBAdzJAm0',
    appId: '1:430397695111:web:9a59fc2c7dbf5f02edc422',
    messagingSenderId: '430397695111',
    projectId: 'luna-staging-2492d',
    authDomain: 'luna-staging-2492d.firebaseapp.com',
    storageBucket: 'luna-staging-2492d.appspot.com',
    measurementId: 'G-VMKVW4VR7H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9I4YO2R6RR29oCAsGW5W8ffxBN2FNWZI',
    appId: '1:430397695111:android:5372c635ef065535edc422',
    messagingSenderId: '430397695111',
    projectId: 'luna-staging-2492d',
    storageBucket: 'luna-staging-2492d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjHHRy1Un-sJ0-UooDNc0ckPzxmZC0sQo',
    appId: '1:430397695111:ios:1734ef273b708252edc422',
    messagingSenderId: '430397695111',
    projectId: 'luna-staging-2492d',
    storageBucket: 'luna-staging-2492d.appspot.com',
    iosBundleId: 'com.valjohn.luna.luna',
  );
}
